jwt:
  time: 90000
  ret: hello-world1234444
posco:
  name: 3기4444
  count: 204444
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enjoy?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234