jwt:
  time: 90000
  ret: hello-world123444455555
posco:
  name: 3기44445555
  count: 20444455555
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enjoy?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234